export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"
export const MEDICINE_GETDATA = "MEDICINE_GETDATA"
export const PATIENTS_GETDATA = "PATIENTS_GETDATA"
export const DOCTORS_GETDATA = "DOCTORS_GETDATA"

export const LOADING_MEDICINES = "LOADING_MEDICINES"
export const LOADING_PATIENTS = "LOADING_PATIENTS"
export const LOADING_DOCTORS = "LOADING_DOCTORS"

export const ERROR_MEDICINES = "ERROR_MEDICINES"
export const ERROR_PATIENTS = "ERROR_PATIENTS"
export const ERROR_DOCTORS = "ERROR_DOCTORS"

export const MEDICINE_ADDDATA = "MEDICINE_ADDDATA"