export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const MEDICINE_GETDATA = "MEDICINE_GETDATA"
export const PATIENTS_GETDATA = "PATIENTS_GETDATA"
export const DOCTORS_GETDATA = "DOCTORS_GETDATA"